07: 29: 58 PM:DEBUG [logger_base.py:13] Mensaje a nivel debug
07: 29: 58 PM:INFO [logger_base.py:14] Mensaje a nivel info
07: 29: 58 PM:WARNING [logger_base.py:15] Mensaje a nivel warning
07: 29: 58 PM:ERROR [logger_base.py:16] Mensaje a nivel error
07: 29: 58 PM:CRITICAL [logger_base.py:17] Mensaje a nivel critical
07: 30: 26 PM:DEBUG [logger_base.py:14] Mensaje a nivel debug
07: 30: 26 PM:INFO [logger_base.py:15] Mensaje a nivel info
07: 30: 26 PM:WARNING [logger_base.py:16] Mensaje a nivel warning
07: 30: 26 PM:ERROR [logger_base.py:17] Mensaje a nivel error
07: 30: 26 PM:CRITICAL [logger_base.py:18] Mensaje a nivel critical
08: 03: 30 PM:DEBUG [Persona.py:56] 
        Id Perons: 1
        Nombre: Juan
        Apellido: Perez
        Email: Juanperez@gmail.com
        
08: 03: 30 PM:DEBUG [Persona.py:58] 
        Id Perons: None
        Nombre: Jose
        Apellido: Lepez
        Email: LepezJose@gmail.com
        
08: 03: 30 PM:DEBUG [Persona.py:60] 
        Id Perons: 1
        Nombre: None
        Apellido: None
        Email: None
        
08: 06: 45 PM:ERROR [conexion.py:26] Ocurrio un error: type object 'Conexion' has no attribute 'DB_PORT'
08: 07: 45 PM:ERROR [conexion.py:25] Ocurrió un error: 'utf-8' codec can't decode byte 0xf3 in position 79: invalid continuation byte
08: 09: 25 PM:DEBUG [conexion.py:24] Conexión exitosa: <connection object at 0x0000016F6D009580; dsn: 'user=postgres password=xxx dbname=test host=127.0.0.1 port=5432', closed: 0>
08: 09: 25 PM:DEBUG [conexion.py:37] Se abrió correctamente el cursor: <cursor object at 0x0000016F6CCADE00; closed: 0>
11: 18: 07 PM:DEBUG [conexion.py:24] Conexión exitosa: <connection object at 0x0000029CA1826130; dsn: 'user=postgres password=xxx dbname=test host=127.0.0.1 port=5432', closed: 0>
11: 18: 07 PM:DEBUG [conexion.py:37] Se abrió correctamente el cursor: <cursor object at 0x0000029CA1E02C00; closed: 0>
11: 18: 40 PM:DEBUG [conexion.py:24] Conexión exitosa: <connection object at 0x00000200E7B5ACE0; dsn: 'user=postgres password=xxx dbname=test host=127.0.0.1 port=5432', closed: 0>
11: 18: 40 PM:DEBUG [conexion.py:37] Se abrió correctamente el cursor: <cursor object at 0x00000200E7BBEC00; closed: 0>
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 1
        Nombre: Juan Ariel
        Apellido: Perez
        Email: JAPerez@gmail.com
        
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 2
        Nombre: Julieta
        Apellido: Quiroga
        Email: juliquiroga@gmail.com
        
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 4
        Nombre: Juan Carlos
        Apellido: Zacas
        Email: ZacasJuan@gmail.com
        
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 5
        Nombre: Juan Pablo
        Apellido: Del Pozzi
        Email: JuanPDP@gmail.com
        
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 6
        Nombre: Marcos
        Apellido: Español
        Email: Españaarriba@gmail.com
        
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 9
        Nombre: Maria
        Apellido: Esperanza
        Email: MaEspe@gmail.com
        
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 10
        Nombre: Maria
        Apellido: Esperanza
        Email: MaEspe@gmail.com
        
11: 18: 40 PM:DEBUG [persona_dao.py:39] 
        Id Perons: 11
        Nombre: Paloma
        Apellido: Quiroga
        Email: Palo@gmail.com
        
